{% set name = "certbot-apache" %}
{% set version = "1.24.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/certbot-apache-{{ version }}.tar.gz
  sha256: d432e6b748ae3d12a794da2a90d3a40a054bcc36c4ff63c303766a685f48b324

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - acme >={{ version }}
    - certbot >={{ version }}
    - python >=3.7
    - python-augeas
    - setuptools >=41.6.0

test:
  imports:
    - certbot_apache
    - certbot_apache._internal
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/letsencrypt/letsencrypt
  summary: Apache plugin for Certbot
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - nehaljwani
