{% set name = "certbot-apache" %}
{% set version = "1.23.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/certbot-apache-{{ version }}.tar.gz
  sha256: d2c92c9d881b2daec989d0a3a607039b5a7cba02f974b89c12c9f43479c01414

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - acme >={{ version }}
    - certbot >={{ version }}
    - python >=3.6
    - python-augeas
    - setuptools >=39.0.1

test:
  imports:
    - certbot_apache
    - certbot_apache._internal
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/letsencrypt/letsencrypt
  summary: Apache plugin for Certbot
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - nehaljwani
