{% set name = "certbot-apache" %}
{% set version = "1.16.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/certbot-apache-{{ version }}.tar.gz
  sha256: 26824b812826d22b3f80377dfc2976a6f37f425c414c50efd8f8bd6e7967d579

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - acme >=0.29.0
    - certbot >=1.6.0
    - python >=3.6
    - python-augeas
    - setuptools >=39.0.1
    - zope.component
    - zope.interface

test:
  imports:
    - certbot_apache
    - certbot_apache._internal
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/letsencrypt/letsencrypt
  summary: Apache plugin for Certbot
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - nehaljwani
